### ISSUE TITLE
Getting error while trying to obtain access token

### ISSUE THREAD

**Issue by amit-bhandari** [smallinvoice/api2-php#1]
endpoint --> https://api.smallinvoice.com/v2/auth/access-tokens

Body --> 
{
    "grant_type":"client_credentials",
    "client_id":"JR5G9PRT0WEMC6SK4AUQ",
    "client_secret":"secret",
    "scope":"PROFILE CONTACTS"
}

response -->

{
    "code": 5,
    "message": "The requested scope is invalid, unknown, or malformed",
    "meta": {
        "error_type": "invalid_scope",
        "hint": "Check the `PROFILE` scope"
    }
}

What I am doing wrong?

**Comment by mischak** [comment]
Maybe the scopes are case sensitive. Did you try with lowercase scope names?

**Comment by amit-bhandari** [comment]
Tried both ways, all caps, none caps. Nothing works

**Comment by mischak** [comment]
When you created your client id, did you check "Profile" in the "Accessible areas"?

**Comment by amit-bhandari** [comment]
I checked every check box while creating id

**Comment by amit-bhandari** [comment]
It would be nice if you could add working example of authorization api in examples for reference.

**Comment by mischak** [comment]
Maybe you better ask for this at the official support channel of Smallinvoice/Lourens Systems

**Comment by amit-bhandari** [comment]
Okay will check with the team itself. Thanks!

**Comment by onlime** [comment]
This must have been resolved by now, but I am still trying to post an answer for the ones that are struggling with this (as smallinvoice API V2 documentation is not complete and does not list scopes anywhere):

When you create a new **OAUTH2-CLIENT-ID** in smallinvoice backend, you can select all available scopes. If you inspect input field values of those checkboxes, you'll find all of the following scopes (lowercase):

```
profile contact contact_reminder letter configuration catalog invoice offer delivery_note order_confirmation project cost_unit working_hours activity effort
```

those scope keys should be self explanatory.
